" gcollura's vimrc

if &compatible
    set nocompatible " Be iMproved
endif
filetype off

let g:vim_dir = expand('<sfile>:p:h')
let s:bundle_dir = g:vim_dir . '/bundle/'
let s:neobundle_dir = s:bundle_dir . 'neobundle.vim/'

if has('vim_starting')
    let &runtimepath .= ',' . s:neobundle_dir
endif

""" Files and backup

" History size
set history=100

" Saving and reloading
set confirm
set autoread
set hidden

" Autosave
au FocusLost * silent! wa

" Encoding
set encoding=utf-8
" Default fileformat.
set fileformat=unix
" Automatic recognition of a new line cord.
set fileformats=unix,dos,mac

" Persistent undo
let &undodir = g:vim_dir . '/undo/' " Where to save undo(s)
set undofile " Save undo when switching buffer or closing files

" Swap files
let &directory = g:vim_dir . '/swap,/tmp'
let &backupdir = g:vim_dir . '/swap,/tmp'

" Folding
set foldmethod=indent " Convenient with C++
set nofoldenable " Folding disable by default
" No folding when loading files
au BufRead * normal zR

""" Editing

" Indentation/tab settings
set autoindent
set smartindent

if v:version > 704 || v:version == 704 && has("patch338")
    set breakindent
endif
set showbreak=\ \

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab

" Change the way backslashes are used in search patterns
set magic

" Turn off word wrapping
set nowrap

" Sane backspace behaviour
set backspace=indent,eol,start

" Set default clipboard
set clipboard+=unnamedplus

" Mouse
set mouse=a

""" Spell Checking

set nospell
set spelllang=en
set spellsuggest=5

""" Completion

set wildmenu
"stuff to ignore when tab completing
set wildignore=*.o,*.png,*.gif,*.jpg,*.jpeg,*.zip,*.jar,*.gem,coverage/**,log/**,*.pyc,*~,build/**

""" Search

set hlsearch
set incsearch
set ignorecase
set smartcase
set gdefault


""" Display

set lazyredraw
set laststatus=2
" Hide show mode while using airline
set noshowmode
" Enable modelines
set modeline

set regexpengine=1

" Numbers
set number
set relativenumber
set numberwidth=5

set scrolloff=4

" Highlight current line
set cursorline

" Column
set textwidth=90
set colorcolumn=+1

" Session options
set sessionoptions=buffers,curdir,tabpages,unix

set pastetoggle=<F9>

if has("win32") || has("win64")
    set shellslash
endif

" Load configurations
execute 'source' fnameescape(g:vim_dir).'/bundles.vim'
execute 'source' fnameescape(g:vim_dir).'/mappings.vim'
execute 'source' fnameescape(g:vim_dir).'/filetype.vim'

" Syntax highlighting and colorscheme
syntax on
if has("gui_running")
    colorscheme base16-monokai
    let g:airline_theme = 'base16'
else
    set background=dark
    set t_Co=256
    let base16colorspace = 256
    colorscheme base16-monokai
    let g:airline_theme = 'base16'
endif
